#ifndef STDCON
#define STDCON

#define MAX_PROCESS_NUM 8
#define MAX_SIGNAL_NUM 64
#define MAX_FILES_PER_PROCESS 3
#define MAX_FILES_PER_SYSTEM 10
#define FAT_IN_MEMORY_SEG 0x6000
#define USER_PROGRAM_IN_MEMORY_SEG 0x7000
#define TEMP_SEG (FAT_IN_MEMORY_SEG - 0x400)
#define MAX_EXENAME_LEN 16
#define MAX_PARAMETER_LEN 48

#endif