set_property PACKAGE_PIN V17 [get_ports cin]
set_property PACKAGE_PIN V16 [get_ports b]
set_property PACKAGE_PIN W16 [get_ports a]
set_property PACKAGE_PIN W17 [get_ports s0]
set_property PACKAGE_PIN W15 [get_ports s1]
set_property PACKAGE_PIN V15 [get_ports s2]
set_property PACKAGE_PIN U16 [get_ports out2]
set_property PACKAGE_PIN E19 [get_ports out1]

set_property IOSTANDARD LVCMOS33 [get_ports cin]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports s0]
set_property IOSTANDARD LVCMOS33 [get_ports s1]
set_property IOSTANDARD LVCMOS33 [get_ports s2]
set_property IOSTANDARD LVCMOS33 [get_ports out2]
set_property IOSTANDARD LVCMOS33 [get_ports out1]
