# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/marse/Documents/digit/project_6_alu/project_6_alu.cache/wt [current_project]
set_property parent.project_path C:/Users/marse/Documents/digit/project_6_alu/project_6_alu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/marse/Documents/digit/project_6_alu/project_6_alu.srcs/sources_1/new/alu.v
read_xdc C:/Users/marse/Documents/digit/project_6_alu/project_6_alu.srcs/constrs_1/new/alu.xdc
set_property used_in_implementation false [get_files C:/Users/marse/Documents/digit/project_6_alu/project_6_alu.srcs/constrs_1/new/alu.xdc]

synth_design -top alu -part xc7a35tcpg236-1
write_checkpoint -noxdef alu.dcp
catch { report_utilization -file alu_utilization_synth.rpt -pb alu_utilization_synth.pb }
